[tool.poetry]
name = "jaundice-assistant"
version = "0.1.0"
description = "Web application to assist in managing jaundice cases."
authors = ["Nawat Ngerncham <n.ngerncham@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [{include = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
flask = "^2.2.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.poetry.scripts]
app = "src.main:run"